# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msisdn',
            name='verif_code',
            field=models.CharField(max_length=12),
        ),
    ]
