# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-12 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=64)),
                ('content_type', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Msisdn',
        ),
        migrations.RemoveField(
            model_name='msisdnurl',
            name='msisdn',
        ),
        migrations.DeleteModel(
            name='MsisdnUrl',
        ),
    ]
