# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20161212_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_dl_ctr',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='content_file',
            field=models.FileField(default='settings.MEDIA_ROOT/tmp/tmp.mms', upload_to='contents/'),
        ),
    ]
